"use client";
import { useEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { VIDEOS, type VideoId } from "@/lib/videos";

// Renders one entry from VIDEOS. Until the real MP4s land, the
// <video> element 404s on src and we fall through to a CSS-driven
// placeholder so layout and transitions are testable.
//
// Conventions enforced here (PRD §3, video infrastructure):
//   - autoPlay + muted + playsInline (the iOS playsInline flag is
//     non-negotiable; without it iPad Safari full-screens the player
//     and breaks the demo)
//   - IntersectionObserver pause when off-screen (iPad GPU budget is
//     tight when the globe is also live)
//   - poster as a still fallback in case the browser blocks autoplay
//   - preload defaults to "none" except for cover_orbit_cinematic on
//     the cover screen (set explicitly via preload="metadata" or
//     "auto" by the caller)
//
// Until the real MP4s land, callers can pass `forcePlaceholder` to
// skip the network request entirely.

interface MissionVideoProps {
  videoId: VideoId;
  className?: string;
  /** "none" | "metadata" | "auto": defaults to "none". */
  preload?: "none" | "metadata" | "auto";
  /** Apply low opacity for use as a background layer. */
  background?: boolean;
  /** Skip the network request and render the placeholder directly.
   *  Useful while the real MP4s are still being regenerated by the
   *  partner. */
  forcePlaceholder?: boolean;
  /** object-fit on the <video>; default "cover". */
  fit?: "cover" | "contain";
  /** ARIA label for screen readers; videos are decorative by default. */
  ariaLabel?: string;
  /** Attribution chip overlaid in the corner. Pass when the clip is
   *  partner / third-party reference material so the platform never
   *  presents external footage as its own output. Defence customers
   *  read uncredited footage as a credibility tell. Position defaults
   *  to bottom-left to clear the typography we usually layer top. */
  attribution?: string;
  attributionPlacement?: "top-left" | "top-right" | "bottom-left" | "bottom-right";
}

export function MissionVideo({
  videoId,
  className,
  preload = "none",
  background,
  forcePlaceholder,
  fit = "cover",
  ariaLabel,
  attribution,
  attributionPlacement = "bottom-left",
}: MissionVideoProps) {
  const entry = VIDEOS[videoId];
  const containerRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [errored, setErrored] = useState(false);
  const [visible, setVisible] = useState(false);

  // Pause when the element scrolls / transitions off-screen.
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      (entries) => {
        const e = entries[0];
        setVisible(!!e?.isIntersecting);
      },
      { threshold: 0.01 },
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  useEffect(() => {
    const v = videoRef.current;
    if (!v || errored) return;
    if (visible) {
      v.play().catch(() => {
        /* autoplay-blocked; poster handles the fallback */
      });
    } else {
      v.pause();
    }
  }, [visible, errored]);

  const showVideo = !errored && !forcePlaceholder;

  return (
    <div
      ref={containerRef}
      className={cn(
        "relative overflow-hidden bg-deep-space",
        background ? "opacity-50" : undefined,
        className,
      )}
      aria-label={ariaLabel}
      role={ariaLabel ? "img" : undefined}
    >
      {showVideo && (
        <video
          ref={videoRef}
          src={entry.src}
          poster={entry.posterSrc}
          preload={preload}
          autoPlay
          muted
          playsInline
          loop={entry.loop}
          onError={() => setErrored(true)}
          className={cn(
            "h-full w-full",
            fit === "cover" ? "object-cover" : "object-contain",
          )}
        />
      )}
      {!showVideo && <Placeholder />}
      {attribution && <Attribution text={attribution} placement={attributionPlacement} />}
    </div>
  );
}

const PLACEMENT_CLASSES: Record<NonNullable<MissionVideoProps["attributionPlacement"]>, string> = {
  "top-left": "top-3 left-3",
  "top-right": "top-3 right-3",
  "bottom-left": "bottom-3 left-3",
  "bottom-right": "bottom-3 right-3",
};

function Attribution({
  text,
  placement,
}: {
  text: string;
  placement: NonNullable<MissionVideoProps["attributionPlacement"]>;
}) {
  return (
    <span
      className={cn(
        "pointer-events-none absolute z-10 inline-flex items-center gap-1.5 rounded-full border border-border/80 bg-background/70 px-2.5 py-1 font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground backdrop-blur-md",
        PLACEMENT_CLASSES[placement],
      )}
    >
      <span className="h-1.5 w-1.5 rounded-full bg-gold/80" aria-hidden />
      {text}
    </span>
  );
}

// Slow drifting radial-gradient. Reads as "loading visual" without
// pretending to be content. Keyed off the video id so multiple slots
// don't synchronise.
function Placeholder() {
  return (
    <div
      className="absolute inset-0"
      style={{
        backgroundImage:
          "radial-gradient(ellipse at 30% 50%, rgba(56,189,248,0.10), transparent 65%), radial-gradient(ellipse at 75% 30%, rgba(212,169,73,0.07), transparent 60%), radial-gradient(ellipse at 50% 80%, rgba(16,185,129,0.05), transparent 70%)",
        animation: "placeholder-drift 22s ease-in-out infinite alternate",
      }}
    />
  );
}
